name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-lib:
    name: Build Lib
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:lib

  build-lib-legecy:
    name: Build Legacy Lib
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:lib:legacy

  build-ce:
    name: Build Custom Element
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:ce

  build-themes:
    name: Build Themes
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:themes

  tests:
    name: Unit Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:test
    - run: npm run test:headless
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./output/coverage/lcov/coverage.lcov
        fail_ci_if_error: true

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: echo ${{ github.event.number }}
    - run: echo ${{ github.repository }}
    - run: echo ${{ github.sha }}
    - run: echo ${{ github.event_name }}

